version: '3.1'

services:
  seed:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - MYSQL_USER=user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - NODE_ADDRESS=^10.0.0.*
    networks:
      - galera_network
    command: seed
    volumes:
      - mysql-new:/var/lib/mysql
    secrets:
      - xtrabackup_password
      - mysql_password
      - mysql_root_password
  node:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - NODE_ADDRESS=^10.0.0.*
      - HEALTHY_WHILE_BOOTING=1
    networks:
      - galera_network
    command: node seed,node
    volumes:
      - mysql-new:/var/lib/mysql
    deploy:
      replicas: 0
    secrets:
      - xtrabackup_password
    ports:
     - 3306:3306
  wordpress:
    depends_on:
      - node
    image: wordpress:4.7.3-php7.1-apache
    ports:
      - 8000:80
#mb same net?
    networks:
      - galera_network 
    volumes:
      - /opt/wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: node:3306 
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: 12345
      WORDPRESS_DB_NAME: database
      WORDPRESS_TABLE_PREFIX: wp_
    deploy:
      mode: replicated
      replicas: 0
      labels: [APP=WORDPRESS]
volumes:
  mysql-new:
    driver: local

networks:
  galera_network:
    driver: overlay

secrets:
  xtrabackup_password:
    file: .secrets/xtrabackup_password
  mysql_password:
    file: .secrets/mysql_password
  mysql_root_password:
    file: .secrets/mysql_root_password
